spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: Thirumal@714
    hikari: { maximum-pool-size: 10, minimum-idle: 2 }
  jpa:
    hibernate: { ddl-auto: update }
    properties: { hibernate: { format_sql: true } }
  flyway: { enabled: true, locations: classpath:db/migration }
server: { port: 8080 }
app: { jwt: { secret: ${APP_JWT_SECRET} } }
management: { endpoints: { web: { exposure: { include: health,info }}}}
