server: { port: 8083 }
spring:
  datasource:
    url: jdbc:h2:mem:evote;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  
  mvc:
    cors:
      mappings:
        allowed-origins: "https://localhost:8443"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
  jpa:
    hibernate: { ddl-auto: validate }
    properties: { hibernate: { format_sql: true } }
  flyway:
    enabled: true
    locations: classpath:db/migration
app:
  jwt:
    secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
management:
  endpoints:
    web:
      exposure: { include: health,info }
