CREATE ROLE admin NOLOGIN;
CREATE ROLE auditor NOLOGIN;
CREATE ROLE app_user NOLOGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PG_APP_USER}') THEN
    CREATE USER ${PG_APP_USER} WITH PASSWORD '${PG_APP_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PG_AUDITOR_USER}') THEN
    CREATE USER ${PG_AUDITOR_USER} WITH PASSWORD '${PG_AUDITOR_PASSWORD}';
  END IF;
END $$;

GRANT app_user TO ${PG_APP_USER};
GRANT auditor TO ${PG_AUDITOR_USER};
GRANT admin TO ${POSTGRES_USER};

CREATE EXTENSION IF NOT EXISTS pgcrypto;
